apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: limtuk3yv-go
  janus-idp.io/tekton: limtuk3yv-go
  backstage.io/kubernetes-id: limtuk3yv-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: limtuk3yv-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
