apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: limtuk3yv-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: limtuk3yv-go 
  name: limtuk3yv-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: limtuk3yv-go 
